= Daemon world terrain

A daemon world is a planet that has been corrupted by the power of Chaos and the Warp.
This is the typical fate of planets that become trapped in a prolonged Warp rift.

These worlds exist as bizarre realms where the laws of physics break down and powerful daemonic entities shape the environment to suit their whims.

== Random terrain generator

.Daemon world terrain generator
[cols="^1h,6*^", options="header"]
////
6 Hill
6 River
6 Road
5 Cliff
5 Temple
3 Graveyard
3 Wood
1 Chaos Plain
1 Fire Storm
////
|===
| D6 | 1    | 2     | 3    | 4      | 5         | 6         
| 1  | Hill | River | Road | Cliff  | Temple    | Graveyard
| 2  | Hill | River | Road | Cliff  | Temple    | Woods
| 3  | Hill | River | Road | Cliff  | Temple    | Woods
| 4  | Hill | River | Road | Cliff  | Temple    | Woods
| 5  | Hill | River | Road | Cliff  | Graveyard | Chaos Plain
| 6  | Hill | River | Road | Temple | Graveyard | Fire Storm
|===

== Terrain types

=== Chaos Plain

This is an area that is subject to one of any number of weird and disturbing effects, such as:
ground that weeps noxious bile that forms many sticky pools of uncertain depth;
a mire in which bony hands emerge to grasp at anything that moves;
localised wisps of energy that shift and flicker and disrupt anything they come into contact with;
an unstable field of dessicated bones and skulls that shift and crack beneath.

.Game effects
Treat as dangerous terrain for all units.

=== Cliff

On a daemon world, a cliff is often more than just a steep rock face.
It might bear a twisted face that moans or screeches at random, or it might be studded with blades and traps that gouge or impale anything that tries to climb it.
Even a cliff that seems ordinary at first might shake and develop landslides that may smother and crush life forms and machinery that approach it.

.Game effects
Treat as impassable for all units -- and perhaps treat as dangerous terrain for all units that pass within 5 cm.

=== Fire Storm

The planet itself abhors interlopers and rages against the armies that are present on this battlefield:
the ground trembles and heaves into eruptions that throw troops and tanks into disarray and force war engines to strain against the upheavals;
the skies manifest meteors that rain down and strike as large, flaming meteorites.
The net effect is extreme disruption across the entire battlefield, which makes it hard for forces to manoeuvre and fight effectively.

.Game effects
Apply a -1 penalty to every Leadership test that the players make during the game.

{blank}[TODO: Either clarify, or consider an alternative here -- as it stands, this represents more of a special rule for the battlefield than a terrain type.]

=== Graveyard

A dismal graveyard or cemetery, or part of some ancient necropolis.
It is studded with a dense array of gravestones, monoliths, tombs, sepulchral chambers and twisted trees.

.Game effects
Treat as woods.
footnote:[
Of course, woods are much taller than cemeteries, so keep that in mind for line of sight purposes -- unless your scenic item represents some towering necropolis built into a hill or rising as a huge, many-tiered construct, of course!
]

=== River

A river on a daemon world is rarely just a river of water -- it is much more likely to be a river of acid, bubbling tar, venomous ooze, daemonic blood, or some other horrifying substance that wends its way across the nightmare landscape.

.Game effects
Treat as usual for a river.

* *Optional*: This river is one of the more troublesome varieties.
Treat it as impassable for Infantry and/or Vehicle units, and as dangerous terrain for War Engine units.

=== Road

The highways and byways of a daemon world tend to be much more exotic than mere tarmac or concrete roads.
Examples of typically weird surfaces include polished obsidian, living flesh, or cobbles made of bone.

.Game effects
Treat as usual for roads.

=== Temple

Followers of Chaos have built a temple in this part of the battlefield.
The appearance and nature of Chaos temples varies wildly -- though there are some common themes that accord with the god or gods that the builders dedicate themselves to.

.Game effects
Use whatever rules you and your opponent agree are most suitable for the temples you wish to represent.
footnote:[{e40k-diff}
{e40k} doesn't offer any particular rules for temples, just a couple of thematic ideas.
We expand on these a little and offer some ideas for rules.
]

However, here are some ideas that you might use or build upon:

.Temple of Slaanesh, the Prince of Pleasure
[%collapsible]
====
An opulent palace, which offers release from mortal misery, but little protection against incoming attacks.
Treat as usual for a building, except as follows:

* Infantry units within do not receive an Infantry Armour bonus (though they do count as 'in cover' on the Firepower table, as usual).
====

.Temple of Khorne, the Blood God
[%collapsible]
====
A fortress-like building, with strong, buttressed walls, heavy, foreboding gates, and armoured towers -- all festooned with spikes that bear the impaled heads of slain foes.
Treat as a fortification, with these extra effects:

* Treat all units within as though they have the {psychic-null} ability.
====

.Temple of Tzeentch, the Changer of Ways
[%collapsible]
====
A conduit for the power of the Warp, characterised by surreal architecture and a nightmare of ever-shifting geometries, colours and pulsating energies.
Treat as usual for a building, with these extra effects:

* During the Shooting phase, each {psyker} unit within can make a single {macro-weapon} shot with a range of 30 cm.
(For simplicity, and to represent the overwhelming force of this attack, treat it just like a regular {macro-weapon} shot as part of the detachment's shooting -- not as a psychic attack that could be cancelled by an appropriate Fate card.)
====

.Temple of Nurgle, The Lord of Decay
[%collapsible]
====
A seething, festering structure, ripe with corruption and filled with the stench of decay -- will likely corrupt, corrode and rot any unit that lingers too long.
Treat as usual for a building, with these extra effects:

* At the start of each turn, for each detachment that has any units within, roll a D6 -- on a 1, a random one of those units takes a hit.
====

.Temple of Chaos Undivided
[%collapsible]
====
An edifice that reflects the worship of all the Chaos Gods as a single pantheon, as emanations of the same universal force.
Treat as usual for a building, with these extra effects:

* In the Rally phase, for any detachment that has units within, players may re-roll their roll to remove Blast markers.
====

=== Woods

On a daemon world, features that look like regular woodlands at a distance often turn out to be far more disturbing and dangerous.
Trees with bark that twists into hideous, screaming faces, and with branches that grasp those who pass within reach... shrubs and undergrowth with spines and thorns and suckers... these are the least of it.
There is an infinite array of weird things that the daemonic rulers of a given daemon world might favour: stands of monstrous arm-like fronds, clusters of giant tentacles, or towering, interconnected fungal growths that are actually one giant organism that roams across the battlefield, on the hunt for prey.

.Game effects
Treat as usual for woods.
You might like to add extra effects, such as:

* Treat the woods as dangerous terrain.
* In the Rally phase, for each detachment that has units in the woods, apply a further -1 modifier when players roll to remove Blast markers.
* 'Walking woods': In the Start phase of each turn, move the woods 2D6 cm in a random direction.

== Other ideas for special rules

The very nature of daemon worlds is that they are chaotic, magical, unstable places of nightmare and impossibility.
So, daemon worlds offer a particularly rich opportunity for you to let your imagination run wild, both in terms of terrain items you could create and the game effects you might associate with them.

Here are some simple ideas, to get you started:

* Perhaps some terrain features can morph into various different forms throughout the battle, and each form has a different game effect.
To determine which form is active, you could randomise each turn, or each time a detachment enters the terrain.
* A given daemon world -- or region thereof -- might have particular effects that apply to the battlefield or armies as a whole.
These effects might represent themes that accord with the particular powers that hold sway here.
For example:
** In a region or world where Khorne is dominant, you might decide that psychic powers simply don't work.
So, perhaps the effects of the {psyker} rules do not apply, and players may not use any form of psychic effect that appears on Fate cards.
** In a region or world where Tzeentch is dominant, you might decide that {psyker} units can channel more psychic energy than usual.
So, perhaps psychic attacks on Fate cards have a stronger effect, or you grant players extra cards which they may use only for their psychic attack function.

.Related information
* xref:core:main-rules:roll-to-remove-blast-markers.adoc[]