= Random terrain generators

How to use the random terrain generators that you'll find in this section, plus some notes on how to create your own generator.

The generators cover a range of different themes, with terrain types that fit the theme in each case.
Many of these terrain types have ideas for rules to make them a little different from the 'standard' terrain types that we include in the core rules.

== How to use the random terrain generators

When you're ready to set up terrain for your game:

. Decide which generator you will use.
. Divide the playing area into 60 cm square sections (or similar, to suit the dimensions of your table).
If you find it helpful, use dice or other objects to temporarily mark the divisions.
. For each section, roll a D3; the score is how many times you should roll on the terrain generator for that section.

Then, for each section, repeat these steps as many times as your D3 score for that section indicates:

. Roll two D6s of different colours -- one colour for the columns of the generator table, the other for the rows.
. Check the scores against the generator you chose, and identify the resultant terrain type.
. Place that terrain type in that section.
(In general, each terrain piece should occupy an area of about 15 to 20 cm square -- although hills and other contours can be quite a bit bigger.)

Finally, arrange the terrain pieces so that they make sense -- not only within each section, but also as a whole.
Don't be afraid to shift things around a bit to make an interesting and believeable battlefield.

== Create your own random terrain generator

Feel free to adjust any of the ready-to-use random terrain generators, or use them as inspiration for your own.

Or, for a quick, generalised solution that you can use with whatever terrain you have to hand:

. Allocate the different types of terrain item in your collection to a letter, A through G.
(You might decide that all hills and contours equate to slot A, woods are slot B, buildings are slot C, and so on.)
. Use this generator:
+
[.scrollable]
--
.Generalised terrain generator
[options="header", cols="^1h,6*^"]
////
9x A
5x B
5x C
5x D
4x E
4x F
4x G
////
|===
| D6 | 1 | 2 | 3 | 4 | 5 | 6
| 1  | A | A | B | C | E | F
| 2  | A | A | B | D | E | F
| 3  | A | A | C | D | E | G
| 4  | A | B | C | D | E | G
| 5  | A | B | C | D | F | G
| 6  | A | B | C | D | F | G
|===
--

.Related information
* xref:get-ready-to-play:set-up-terrain.adoc[]