= Random terrain generators

How to use the random terrain generators that you'll find in this section, plus some notes on how to create your own generator.

The generators cover a range of different themes, with terrain types that fit the theme in each case.
Many of these terrain types have ideas for rules to make them a little different from the 'standard' terrain types that we list in the core rules.

== How to use random terrain generators

When you're ready to set up terrain for your game:

. Decide which generator you will use.
. Divide the playing area into 60 cm square sections (or similar, to suit the dimensions of your table).
If you find it helpful, use dice or other objects to temporarily mark the divisions.
. For each section, roll a D3; the score is how many times you should roll on the terrain generator for that section.

Then, for each section, repeat these steps as many times as your D3 score for that section indicates:

. Roll two D6s of different colours -- one colour for the columns of the generator table, the other for the rows.
. Check the scores against the generator you chose, and identify the resultant terrain type.
. Place that terrain type in that section.
(In general, each terrain piece should occupy an area of about 15 to 20 cm square -- although hills and other contours can be quite a bit bigger.)
. Arrange all terrain types you generate for that section in a way that makes sense -- but don't be afraid to adjust terrain again after you've generated the final section.

== Create your own random terrain generator

Feel free to adjust any of the ready-to-use random terrain generators, or use them as inspiration for your own.

Or, allocate the different types of terrain item in your collection to a letter, A through G.
(You might decide that all hills and contours equate to slot A, woods are slot B, buildings are slot C, and so on.)
And then use the following generator:

.Create-your-own random terrain generator table
[cols="1h,6*", options="header"]
|===
| D6 | 1 | 2 | 3 | 4 | 5 | 6
| 1  | A | C | B | C | C | C
| 2  | B | C | F | E | C | A
| 3  | C | D | A | D | A | B
| 4  | D | A | C | D | G | C
| 5  | E | G | E | G | E | F
| 6  | F | E | G | F | B | F
|===

.Related information
* xref:get-ready-to-play:set-up-terrain.adoc[]