= Objectives

Some scenarios specify that you must set up markers to represent battlefield objectives that the opposing armies seek to attain or to deny to their enemy.

Such scenarios explain what objective markers to place.
They may also include special instructions that add to or over-ride the default rules that we explain here.

== General rules for objectives and objective markers

=== Placement

There are various <<objective-types, types of objective>>, and each type has specific restrictions on where you can place corresponding markers.
However, you must also observe these general restrictions by default:

* You may not place any objective marker within 15 cm of any of your other objective markers.
* You may not place any objective marker within 15 cm of the edge of the playing area -- unless the scenario specifies that your forces enter from that edge.
(In effect, that table edge is the leading edge of your deployment zone.)

TIP: We recommend that you base all objective-related measurements on the centres of the markers rather than on their edges.
This gives you a bit more room to place them and means that it doesn't really matter exactly how big or small each marker is.

=== Control

For the most part, you can only benefit from your own objectives.
Except where the rules say otherwise, you gain nothing from control of your opponent's objectives.

Of course, it is in your interests to prevent your opponent from getting the benefits of their objectives.

[[objective-types]]
== Types of objective/objective marker

The standard objective types and their default rules are as follows.

{blank}[TODO: We should tweak the 'R4. Check the game end conditions' topic and the 'End of turn' part of the turn sequence, and rationalise how we refer to objectives and Morale effects that we check or apply 'in the Rally phase' or 'at the end of the turn'. At present, the arrangement incorrectly implies that some Morale effects happen *after* we check for the game end conditions in the turn sequence.]

=== Take & Hold
This objective represents a location on the battlefield that is vital or highly advantageous to hold for as long as possible in the face of the enemy.

[none]
* *Placement*:
You must place the objective marker either in your opponent's deployment zone or more than 90 cm away from your deployment zone.
* *Game effects and control*:
At the end of the Rally phase:
If you have a unit that is within 15 cm of your Take & Hold objective marker *and* closer to it than any enemy units, then you are in control of this objective this turn.
* *Morale effect*:
At the end of each Rally phase:
For each Take & Hold objective that you control, add D3 points to your Army Morale value.

=== Rescue
This objective represents something that is significant to both sides in the conflict -- something that both sides wish to control, to the exclusion of the other.
Vital plans perhaps, or an important hostage.

[none]
* *Placement*:
You must place the objective marker more than 90 cm away from your deployment zone *and* within a terrain feature that offers an Infantry Armour bonus for cover.
* *Game effects and control*:
When a player moves a ground unit that they control onto the objective marker, they may use that unit to 'pick up' the objective.
We call this the 'escort unit'.
** The player can then continue to use the escort unit entirely as normal for its type -- it's just that the objective travels with it.
** If the escort unit is destroyed, leave the objective marker at that point on the playing surface -- leave the marker there until *either* player moves a unit they control over it, picks it up, and becomes the current escort unit.
** If the escort unit is destroyed in *close combat* then, if there is a surviving enemy unit that was in base contact with the escort unit, the opposing player may declare this unit as the new escort unit and pick up the objective immediately.

+
NOTE: To be clear, only you can make the initial pick up of your Rescue objective.
However, once you have done this, it is possible for your opponent to destroy your escort unit and then have one of their units pick up your unescorted Rescue objective and become the current escort unit, as we explain above.
* *Morale effect*:
At the end of each Rally phase:
For each of your units that has a Rescue objective (that is, for each of your units that currently count as an escort unit), apply *both* of these effects:
** Add 1 point to your Army Morale value.
** Your opponent must deduct 1 point from their Army Morale value.

=== Bunker
This objective represents something of particular value to the enemy that you want to destroy to hinder them in some way -- a site of strategic or tactical value such as a command bunker, communications relay or missile silo.

[none]
* *Placement*:
You must place this objective marker inside your opponent's deployment zone.
* *Game effects and control*:
The bunker objective marker represents a static unit that has these characteristics:
+
include::partial$bunker-data-sheet.adoc[]
+
Your goal with this objective is to use shooting and/or assaults to attack and destroy the bunker.
+
** Treat the marker as if it were an enemy War Engine unit that is in the Immobilised condition.
** If it suffers critical damage, it is destroyed, irrespective of any remaining Damage Capacity.
** In an assault, enemy units that are within 15 cm of the bunker objective marker can lend support during the Assault phase.
+
{blank}[TODO: Clarify. My guess is that the intent is for such units to lend support, but not for this alone to cause their detachment to count as engaged in the assault... but I'm not sure.]
* *Morale effect*:
When you destroy your bunker objective, roll a D6 -- your opponent must immediately deduct the score from their Army Morale value.
+
Then remove the objective marker from the playing area.

=== Capture
This objective represents something of particular one-time value to your army -- such as a fuel dump or an ammunition store.
When your forces capture it they exploit it immediately and continue with the battle.

[none]
* *Placement*:
You must place this objective in your opponent's deployment zone.
* *Game effects and control*:
At the end of the Rally phase:
If you have a unit in base contact with your Capture objective marker, then you control this objective.
* *Morale effect*:
At the end of the Rally phase:
For each of your Capture objectives that you control at the end of a turn, choose and apply *one* of these effects:
** *Capture*: Add D6 points to your Army Morale value.
** *Destroy*: Your opponent must subtract D6 points from their Army Morale value.

+
Then remove the objective marker from the playing area.

=== Cleanse
This objective represents an area that you want to keep out of the enemy's hands.

[none]
* *Placement*:
You must place this objective marker inside your own deployment zone.
* *Game effects and control*:
At the end of the Rally phase:
If you have a unit that is within 15 cm of your Cleanse objective marker *and* closer to it than any enemy units, then you control the objective.
* *Morale effect*:
At the end of each Rally phase:
For each of your Cleanse objectives that you control, add 1 point to your Army Morale value.

---

.Related information
* xref:core:ROOT:what-you-will-need-to-play.adoc#objective-markers[Objective markers]
* xref:core:main-rules:terrain-effects-on-shooting.adoc#infantry-armour-bonus[Armour bonus for infantry that are in cover]