A summary of the morale effects of the standard objectives  -- for full detail see xref:battles:scenario-special-rules:objectives.adoc[].

[%collapsible]
.Take & Hold
====
_Ongoing effect: Check at the end of each Rally phase._

For each of your Take & Hold objectives that you control, add D3 points to your Army Morale value.
====

[%collapsible]
.Rescue
====
_Ongoing effect: Check at the end of each Rally phase._

For each of your units that has a Rescue objective (that is, for each of your units that currently count as an escort unit), apply both of these modifiers:

* Add 1 point to your Army Morale value.
* Your opponent must deduct 1 point from their Army Morale value.
====

[%collapsible]
.Bunker
====
_One-time effect: Each time you destroy one of your bunker objectives._

Roll a D6 -- your opponent must immediately deduct the score from their Army Morale value.
====

[%collapsible]
.Capture
====
_One-time effect: Check at the end of each Rally phase._

For each of your Capture objectives that you control, choose and apply one of these modifiers:

* *Capture*: Add D6 points to your Army Morale value.
* *Destroy*: Your opponent must subtract D6 points from their Army Morale value.
====

[%collapsible]
.Cleanse
====
_Ongoing effect: Check at the end of each Rally phase._

For each of your Cleanse objectives that you control, add 1 point to your Army Morale value.
====