= Battle 2: Escalating Engagement

In a less contested sector of the battle front, two patrols from opposing armies run into each other.
As they clash, both sides call in reinforcements.

== Scenario special rules

xref:scenario-special-rules:army-morale.adoc[]; xref:scenario-special-rules:objectives.adoc[]; xref:scenario-special-rules:reserves.adoc[]

== Armies

include::partial$agree-a-maximum-points-value-limit.adoc[]

== Maps

NOTE: The original {e40k} texts are ambiguous and it's not clear exactly what 'edges' we should use for Reserves in this scenario.
We have not yet settled on a particular interpretation, so there's a good chance that we'll change some of the details that you see here.

* Non-standard deployment edges -- refer to the map.
* The two deployment zones represent the areas that opposing detachments are patrolling at the moment they sight each other.
The deployment zones are in opposite corners of the playing area, 150 cm apart.
Each is 90 cm deep, with a width that depends upon the width of your playing area (15 cm by default).

image::map-battle-2-escalating-engagement-1.svg[alt="Deployment map for the Escalating Engagement scenario (long deployment edge)",600,450]

[none]
.Legend
* [.conum]#A# Deployment zone A.
* [.conum]#B# Deployment zone B.

////
[.float-group]
--
[.left]
.Long deployment edge
image::map-battle-2-escalating-engagement-long.svg[alt="Deployment map for the Escalating Engagement scenario (long deployment edge)",392,294]

[.left]
.Short deployment edge
image::map-battle-2-escalating-engagement-short.svg[alt="Deployment map for the Escalating Engagement scenario (short deployment edge)",392,294]

[.left]
.Corner deployment edge
image::map-battle-2-escalating-engagement-corner.svg[alt="Deployment map for the Escalating Engagement scenario (corner deployment edge)",392,294]
--
////

== Setup

. xref:get-ready-to-play:set-up-terrain.adoc[Set up terrain] in the standard way.
include::partial$choose-deployment-edge-zone.adoc[]
. Choose your xref:scenario-special-rules:objectives.adoc[objectives], as follows:
* Each player must have one objective per 500 points in their army (round fractions up).
You may each choose or pick at random from any of the standard objectives.
+
.Number of objectives
====
In a game with a limit of 1,800 points for each army, you will each have four objectives.
====
. Place your objective markers in the standard way.

== Disposition of forces

Determine the disposition of your forces.

. Place all of your Flyer detachments in xref:scenario-special-rules:reserves.adoc[Reserves].
. If you have any detachments that qualify for the Reserves rules on their own merit, place them in Reserves.
. You must deploy a single detachment during initial deployment, to represent your patrol force.
This must be the Infantry/Vehicle detachment that has the lowest points value in the your army, except that it cannot be your Supreme commander detachment.
+
--
* To be clear: Even if it is the lowest points value detachment in your army, do not use a War Engine or Flyer or Supreme Commander detachment for your patrol.
--
+
Keep your 'patrol detachment' at hand for your initial deployment.
. Place all of your remaining detachments in Reserves.

== Initial deployment

The player whose army has the lower Strategy Rating must deploy their patrol detachment first, in their deployment zone.
Then the opposing player must deploy their patrol detachment in their deployment zone.

== Play the game

Start the game in the usual way: Proceed to the Start phase.

== Game length and victory conditions

include::partial$standard-army-morale-win-conditions.adoc[]

* If this hasn't happened by the end of the 6^th^ turn, then the player with the higher Army Morale value wins a 'tactical victory'.
* If both players' Army Morale values drop to 0 or less on the same turn, then the player with the higher Army Morale value wins a 'tactical victory'.