= Battle 4: Blitzkrieg!

A rapid offensive has penetrated into lightly defended enemy territory.
The attackers must swiftly overcome scattered resistance and seize objectives before fresh defenders appear.

== Scenario special rules

xref:scenario-special-rules:army-morale.adoc[]; xref:scenario-special-rules:fortifications.adoc[]; xref:scenario-special-rules:hidden-setup.adoc[]; xref:scenario-special-rules:objectives.adoc[]; xref:scenario-special-rules:reserves.adoc[]

== Armies

include::partial$agree-a-maximum-points-value-limit.adoc[]

== Maps

* Standard deployment edges, but the Defender can also bring Reserves into play along all edges except for the Attacker's deployment edge -- refer to the maps.
* The Defender's deployment zone covers the entire table, except within 20 cm of the Attacker's deployment edge.
* The Attacker's has no deployment zone, only a deployment edge.

[.float-group]
--
[.left]
.Long deployment edge
image::map-battle-4-blitzkrieg-long.svg[alt="Deployment map for the Blitzkrieg! scenario (long deployment edge)",392,294]

[.left]
.Short deployment edge
image::map-battle-4-blitzkrieg-short.svg[alt="Deployment map for the Blitzkrieg! scenario (short deployment edge)",392,294]

[.left]
.Corner deployment edge
image::map-battle-4-blitzkrieg-corner.svg[alt="Deployment map for the Blitzkrieg! scenario (corner deployment edge)",392,294]

[none.left]
.Legend
* [.conum]#D# Defender's deployment zone.
--

== Setup

. Determine who will be the *Attacker* and who will be the *Defender*.
. xref:get-ready-to-play:set-up-terrain.adoc[Set up terrain] in the standard way.
. *Defender*: Chooses which deployment edge the *Attacker* must use for deployment.
You may choose a standard short edge, long edge or corner -- but usually you'll find it more to your advantage to give the Attacker a short deployment edge (see <<Maps>>).
. Choose your xref:scenario-special-rules:objectives.adoc[objectives], as follows:
* *Attacker*: You must must have one objective per 500 points in your army (round fractions up).
You may use any objectives, except for Rescue and Cleanse.
You may either choose from among those available, or pick at random.
* *Defender*: You must have one objective per 1,000 points in your army (round fractions *down*).
You may use only Cleanse objectives.
+
.Number of objectives
====
In a 1,500 point game, the Attacker will have three objectives and the Defender will have one.
====
. Place your objective markers.
The Attacker must be first to place an objective marker, and then the players alternate until they have placed all of their objective markers.
+
IMPORTANT: You must place all objective markers in the Defender's half of the table.
Apply other placement restrictions that don't conflict with this as normal.

== Disposition of forces

*Attacker*: Determine the disposition of your forces.

. Place all of your Flyer detachments in xref:scenario-special-rules:reserves.adoc[Reserves].
. If you have any detachments that qualify for the Reserves rules on their own merit, place them in Reserves.
. Keep the rest of your detachments at hand for initial deployment.


*Defender*: Determine the disposition of your forces.

. Roll a D6 for each detachment in your army:
+
--
[none]
* *1 to 5*: This detachment is part of your reinforcements -- place it in xref:scenario-special-rules:reserves.adoc[Reserves].
* *6*: This detachment is part of your immediate defences.
If it is a Flyer detachment, place it aside ready to bring into play in the first turn of the game.
Otherwise, keep it at hand for your initial deployment.
{blank}[TODO: What if it is a detachment that qualifies for the Reserves rules on it's own merit? Place it aside ready to bring into play in the first turn of the game?]
--
+
You must deploy at least one detachment during initial deployment.
So, if you did not roll 6 for any of your non-Flyer detachments then you must randomly determine one detachment to keep at hand for this purpose.

== Initial deployment

. *Defender*: You must deploy first.
* Deploy all of the detachments that you kept at hand for your initial deployment.
* Deploy within the Defender's deployment zone [.conum]#D# (see <<Maps>>).
* For Infantry/Vehicle detachments, use the xref:scenario-special-rules:hidden-setup.adoc[] rules.
* You may also use xref:scenario-special-rules:fortifications.adoc[] if you wish.
+
{blank}[TODO: The original text is ambiguous -- there's the requirement to use the Hidden Setup rules for Infantry/Vehicle detachments, and then the final bullet states that "all remaining defending detachments are in reserve at the start of the battle" -- does this imply that War Engine detachments, which you can't hide, should be in Reserves?]
+
You may bring your Reserves detachments into play anywhere along any edge except for the Attacker's deployment edge (see <<Maps>>).

. *Attacker*: Do not deploy any detachments yet.
Instead, place HQ units to indicate where the detachments that you kept at hand for initial deployment will enter play during the game.
.. Pick an HQ unit to be first, and place it to indicate any point along your deployment edge.
.. Each other HQ unit you place must indicate a point that is on your deployment edge *and* within 15 cm of the point that your first HQ unit indicates.
.. You may 'stack' multiple HQ units in a column, to indicate the same point on your deployment edge -- you might want to do this where a road crosses the table edge, for example.
.. You may choose one detachment per 1,000 points of the maximum points value limit (or part thereof -- round up) to be a *flanking* detachment, if you wish.
You may place the HQ units of your flanking detachments to indicate any point along your deployment edge, rather than only within 15 cm of the point you indicated with the first HQ unit you placed.

== Play the game

Start the game in the usual way: Proceed to the Start phase.

*Attacker*: When you reach the first Movement phase and it is your turn to complete your moves, put into play the detachments that correspond to the HQ units you placed.
Each time you put a detachment into play, measure the movement of its units -- including its HQ unit -- from the point that its HQ unit indicates on your deployment edge.

== Game length and victory conditions

include::partial$standard-army-morale-win-conditions.adoc[]

include::partial$fallback-win-conditions-victory-points.adoc[]