= Battle 3: Dawn Assault

A formidable attacking force means to surprise and overwhelm the enemy's smaller defensive force.
However, the defensive force is concealed in prepared positions among minefields and booby-traps.
The attackers must be bold to find the defenders and overrun them before their reinforcements can turn the tide of battle.

== Scenario special rules

xref:scenario-special-rules:army-morale.adoc[]; xref:scenario-special-rules:fortifications.adoc[]; xref:scenario-special-rules:hidden-setup.adoc[]; xref:scenario-special-rules:objectives.adoc[]; xref:scenario-special-rules:reserves.adoc[]

== Armies

include::partial$agree-a-maximum-points-value-limit.adoc[]

== Maps

* Standard deployment edges, but the Defender can also bring Reserves into play along adjacent edges that extend to the half-way line.
* The Defender's deployment zone extends from their deployment edge to the half-way line.
* The Attacker's deployment zone extends from their deployment edge to 20 cm onto the table.

[.float-group]
--
[.left]
.Long deployment edge
image::map-battle-3-dawn-assault-long.svg[alt="Deployment map for the Dawn Assault scenario (long deployment edge)",392,294]

[.left]
.Short deployment edge
image::map-battle-3-dawn-assault-short.svg[alt="Deployment map for the Dawn Assault scenario (short deployment edge)",392,294]

[.left]
.Corner deployment edge
image::map-battle-3-dawn-assault-corner.svg[alt="Deployment map for the Dawn Assault scenario (corner deployment edge)",392,294]

[none.left]
.Legend
* [.conum]#A# Attacker's deployment zone.
* [.conum]#D# Defender's deployment zone.
--

== Setup

. Decide who will be the *Attacker* and who will be the *Defender*.
. xref:get-ready-to-play:set-up-terrain.adoc[Set up terrain] in the standard way.
include::partial$choose-deployment-edge-zone.adoc[]
. Choose your xref:scenario-special-rules:objectives.adoc[objectives], as follows:
* *Attacker*: You must have one objective per 500 points in your army (round fractions up).
You may use any objectives, except for Rescue and Cleanse.
You may either choose from among those available, or pick at random.
* *Defender*: You must have one objective per 1,000 points in your army (rounding fractions *down)*.
You may use only Cleanse objectives.
+
.Number of objectives
====
In a 1,500 point game, the Attacker will have three objectives and the Defender will have one.
====
. Place your objective markers.
+
IMPORTANT: You must place all objectives in the Defender's half of the table.
This is in addition to any other restrictions that normally apply to them.
+
The Attacker places the first objective marker and then the players alternate until they have placed all of the objective markers.

== Disposition of forces

*Attacker*: Determine the disposition of your forces.

. Place all of your Flyer detachments in xref:scenario-special-rules:reserves.adoc[Reserves].
. If you have any detachments that qualify for the Reserves rules on their own merit, place them in Reserves.
. Keep all of your other detachments at hand for your initial deployment.


*Defender*: Determine the disposition of your forces.

. Roll a D6 for each detachment in your army:
+
--
[none]
* *1 to 3*: This detachment is part of your reinforcements -- place it in xref:scenario-special-rules:reserves.adoc[Reserves].
* *4 to 6*: This detachment is part of your immediate defences.
If it is a Flyer detachment, place it aside ready to bring into play in the first turn of the game.
Otherwise, keep it at hand for your initial deployment.
{blank}[TODO: What if it is a detachment that qualifies for the Reserves rules on it's own merit? Place it aside ready to bring into play in the first turn of the game?]
--
+
You must deploy at least one detachment during initial deployment.
So, if you did not roll 4 to 6 for any of your non-Flyer detachments then you must choose which detachment you will keep at hand for this purpose.

== Initial deployment

. *Defender*: You must deploy first.
* Deploy all of the detachments that you kept at hand for your initial deployment.
* Deploy within the Defender's deployment zone [.conum]#D# (see <<Maps>>).
* For Infantry/Vehicle detachments, use the xref:scenario-special-rules:hidden-setup.adoc[] rules.
* You may also use xref:scenario-special-rules:fortifications.adoc[] if you wish.
+
{blank}[TODO: The original text is ambiguous -- there's the requirement to use the Hidden Setup rules for Infantry/Vehicle detachments, and then it states that "all remaining defending detachments are in reserve at the start of the battle" -- does this imply that War Engine detachments, which you can't hide, should be in Reserves?]
+
You may bring your Reserves detachments into play anywhere along the edges that include the Defender's deployment edge and up to half-way along the two adjacent edges of the table (see <<Maps>>).

. *Attacker*: Deploy within the Attacker's deployment zone [.conum]#A# (see <<Maps>>).
You may bring your Reserves detachments into play anywhere along the Attacker's deployment edge.

== Play the game

Start the game in the usual way: Proceed to the Start phase.

== Game length and victory conditions

include::partial$standard-army-morale-win-conditions.adoc[]

include::partial$fallback-win-conditions-victory-points.adoc[]