= Battle 6: Planetary Assault

The initial efforts to land forces from orbit and gain a foothold on a planet have led to some of the bloodiest battles in the 41^st^ millennium.
Here, a defending force must fight with all the ferocity it can muster to repel the attacking force that seeks to secure and expand its landing zone.

== Scenario special rules

xref:scenario-special-rules:army-morale.adoc[]; xref:scenario-special-rules:drop-pods.adoc[]; xref:scenario-special-rules:fortifications.adoc[]; xref:scenario-special-rules:hidden-setup.adoc[]; xref:scenario-special-rules:objectives.adoc[]; xref:scenario-special-rules:reserves.adoc[]

== Armies

include::partial$agree-a-maximum-points-value-limit.adoc[]

This scenario does not lend itself well to a randomised approach in which you choose balanced armies in advance and then randomise which army will attack and which will defend.
Instead, we recommend that you decide in advance which player will be the Attacker and which the Defender -- and then build specialist armies as appropriate.

== Maps
footnote:[{e40k-diff}
In the original text, it's not entirely clear whether or not the corner deployment edge option was intended.
There's an ambiguous use of the phrase "single table edge" which could imply only actual physical table edges (long or short), as opposed to a conceptual deployment edge (long, short, or corner).
We don't think it matters though, so we decided to include the corner option rather that rule it out.
]

* Non-standard deployment edges: *After* the Defender completes their initial deployment in their deployment zone, the Attacker chooses a deployment edge that they will use to bring their Reserves into play.
The Defender then gets all remaining edges to bring their Reserves into play.
* The Defender's deployment zone covers the entire table, except within 15 cm of each table edge.
* The Attacker has no deployment zone, only the deployment edge that they choose after the Defender completes their initial deployment.

[.float-group]
--
[.left]
.Long deployment edge
image::map-battle-6-planetary-assault-long.svg[alt="Deployment map for the Planetary Assault scenario (long deployment edge)",392,294]

[.left]
.Short deployment edge
image::map-battle-6-planetary-assault-short.svg[alt="Deployment map for the Planetary Assault scenario (short deployment edge)",392,294]

[.left]
.Corner deployment edge
image::map-battle-6-planetary-assault-corner.svg[alt="Deployment map for the Planetary Assault scenario (corner deployment edge)",392,294]

[none.left]
.Legend
* [.conum]#D# Defender's deployment zone.
--

== Setup

. Determine who will be the *Attacker* and who will be the *Defender*.
. xref:get-ready-to-play:set-up-terrain.adoc[Set up terrain] in the standard way.
. Unlike most scenarios, you do not determine deployment edges at this point -- but the Defender automatically gets the Defender's deployment zone as we show at <<Maps>>.
. Choose your xref:scenario-special-rules:objectives.adoc[objectives], as follows:
* *Attacker*: You must have one objective per 500 points in your army (round fractions *up*).
You may use any objectives, except for Rescue and Cleanse.
Either choose from among those available, or pick at random.
* *Defender*: You must have one objective per 1,000 points in your army (round fractions *down)*.
You may use only Cleanse objectives.
+
.Number of objectives
====
In a 1,500 point game, the Attacker will have three objectives and the Defender will have one.
====
. Place your objective markers.
The Attacker must place one of their objective markers first, then alternate until both players have have placed all of their objective markers.

== Disposition of forces

*Attacker*: Determine the disposition of your forces.
You may do this *after* you see the defender's initial deployment, if you wish.
footnote:[
This probably doesn't really matter, but the order of the steps in {e40k} implies that this is the case -- so we provide the option.
]

. Split your army into two parts, to represent two separate assault waves:
* The part that represents the first assault wave *must* contain all of your army's Flyer detachments, and *may* contain any other detachments.
This part is available for you to deploy in the first turn of the game -- but you may only bring troops in this part into play if they are transported by Flyer transport units, or if they are valid Drop Pods detachments.
+
{blank}[TODO: Clarify: Exactly what does the term 'troops' mean here? The natural assumption is that it means Infantry units, but it seems like it should actually mean all valid 'cargo' units -- which can include Vehicle units in some cases (and could potentially include specific War Engine units in this project in due course)? What if this part includes units that don't qualify and must be left behind? Should we apply a note like that in Meeting Engagement about counting them as destroyed, or should we reformat the instructions so that this can't happen, or... something else?]
+
{blank}[TODO: Clarify: What about other detachments that qualify for the Reserves rules on their own merit, aside from Drop Pods? I seem to recall text somewhere that states something to the effect that "Tunnellers don't count as Drop Pods for the Planetary Assault scenario" -- but should any other detachments count, through the {deep-strike} ability or whatever?]
* The part that represents the second assault wave contains all the rest of detachments in your army.
(We assume that the attacking army landed these detachments in the nearby landing zone in light orbital transports that they didn't want to risk in a 'hot' landing zone.)
Place all detachments in this part in xref:scenario-special-rules:reserves.adoc[Reserves], to enter play under the normal Reserves rules.
+
{blank}[TODO: Clarify: Is there any minimum requirement for the second assault wave, such as at least one detachment? Otherwise there could be just the first assault wave, no second wave -- is this intended/acceptable?]


*Defender*: Determine the disposition of your forces.

. Place all of your War Engines detachments in xref:scenario-special-rules:reserves.adoc[Reserves].
. Aside from the above, roll a D6 for each detachment in your army:
+
--
[none]
* *1 to 3*: This detachment is part of your reinforcements -- place it in xref:scenario-special-rules:reserves.adoc[Reserves].
* *4 to 6*: This detachment is part of your immediate defences.
If it is a Flyer detachment, place it aside ready to bring into play in the first turn of the game.
If it is an Infantry and/or Vehicle detachment, keep it at hand for your initial deployment.
{blank}[TODO: What if it is a detachment that qualifies for the Reserves rules on it's own merit? Place it aside ready to bring into play in the first turn of the game?]
--
+
You must deploy at least one detachment during initial deployment.
So, if you did not roll 4 to 6 for any of your non-Flyer detachments then you must randomly determine one detachment to keep at hand for this purpose.

== Initial deployment

. *Defender*: You must deploy first.
* Deploy within the Defender's deployment zone [.conum]#D# (see <<Maps>>).
* Use the xref:scenario-special-rules:hidden-setup.adoc[] rules to deploy all of the detachments that you kept at hand for your initial deployment.
* You may also use xref:scenario-special-rules:fortifications.adoc[] if you wish.

. *Attacker*: Choose a deployment edge (see <<Maps>>).
This represents the proximity of your army's primary landing zone, and is where you can bring your Reserves detachments into play later.
The Defender may use any or all of the other edges to bring their Reserves detachments into play later.

. *Attacker*: You have no initial deployment -- all your forces arrive in the first turn or later (see <<Disposition of forces>>).

== Play the game

Start the game in the usual way: Proceed to the Start phase.

*Defender*: In the first turn only, when any of your hidden detachments are revealed, roll a D6:

* *1 to 3*: The attackers surprise this detachment, and it is now in disarray.
Place an Order marker to indicate that it is subject to the Broken condition.
(The standard rules apply, so you can try to rally the detachment in the Rally phase).
* *4 to 6*: The detachment is alert and ready for battle.
You may use it as normal.

== Game length and victory conditions

include::partial$standard-army-morale-win-conditions.adoc[]

include::partial$fallback-win-conditions-victory-points.adoc[]