= Battle 1: Meeting Engagement

Two opposing armies rush to secure a strategically important area; and they arrive at the same time.
As they meet, each army seeks to gain the advantage as it scrambles to deploy from its column of march as effectively as it can.

== Scenario special rules

xref:scenario-special-rules:army-morale.adoc[]; xref:scenario-special-rules:objectives.adoc[]

== Armies

include::partial$agree-a-maximum-points-value-limit.adoc[]

== Maps

* Standard deployment edges.
* No deployment zones.

[.float-group]
--
[.left]
.Long deployment edge
image::map-battle-1-meeting-engagement-long.svg[alt="Deployment map for the Meeting Engagement scenario (long deployment edge)",392,294]

[.left]
.Short deployment edge
image::map-battle-1-meeting-engagement-short.svg[alt="Deployment map for the Meeting Engagement scenario (short deployment edge)",392,294]

[.left]
.Corner deployment edge
image::map-battle-1-meeting-engagement-corner.svg[alt="Deployment map for the Meeting Engagement scenario (corner deployment edge)",392,294]
--

== Setup

. xref:get-ready-to-play:set-up-terrain.adoc[Set up terrain] in the standard way.
include::partial$choose-deployment-edge-zone.adoc[]
. Choose your xref:scenario-special-rules:objectives.adoc[objectives], as follows:
* Each player must have one objective per 500 points in their army (round fractions up).
You may each choose up to one Rescue objective -- the rest must all be Take & Hold.
+
.Number of objectives
====
In a game with a limit of 1,800 points for each army, you will each have four objectives.
====
. Place your objective markers in the standard way.

== Initial deployment

Do not deploy any detachments yet.
Instead, place HQ units to indicate where your detachments will enter play during the game.

NOTE: Don't place HQ units for Reserves detachments -- apply the Reserves rules as normal.

Start with the player whose army has the lower Strategy Rating and alternate between you until there are no more HQ units to place:

. Pick an HQ unit to be first, and place it to indicate any point along your deployment edge.
. Each other HQ unit you place must indicate a point that is on your deployment edge *and* within 15 cm of the point that your first HQ unit indicates.
You may 'stack' multiple HQ units in a column, to indicate the same point on your deployment edge -- you might want to do this where a road crosses the table edge, for example.
. Each player may choose one detachment per 1,000 points of the maximum points value limit (or part thereof -- round up) to be a *flanking* detachment, if they wish.
You may place the HQ units of your flanking detachments to indicate any point along your deployment edge, rather than only within 15 cm of the point you indicated with the first HQ unit you placed.

== Start the game

Start the game in the usual way: Proceed to the Start phase.

When you reach the first Movement phase and it is your turn to complete your moves, put into play the detachments that correspond to the HQ units you placed.
Each time you put a detachment into play, measure the movement of its units -- including its HQ unit -- from the point that its HQ unit indicates on your deployment edge.

IMPORTANT: Aside from Reserves detachments, any detachment that does not enter play in the first turn counts as destroyed -- deduct the detachment's Morale value from your Army Morale total, as normal for a destroyed detachment.
footnote:[
We consider the detachment to be 'destroyed' for the sake of the battle, but not for the war.
That is, treat the detachment as destroyed for all rules purposes in the current game -- but not for future games, if you're playing a campaign.
]
footnote:[{e40k-diff}
The link:https://thehobby.zone/resources/e40k-compendium/Content/Battles/TheScenarios/Battle1MeetingEngagement.htm[original text for this scenario^] is ambiguous as it merely states that such detachments 'are lost'.
We've defined some definite consequences that are consistent with other unusual but similar situations that we've defined elsewhere.
]

== Game length and victory conditions

include::partial$standard-army-morale-win-conditions.adoc[]

* If this hasn't happened by the end of the 4^th^ turn, then the player with the higher Army Morale value wins a 'tactical victory'.
* Or, if you both agree, you could play for as many turns as it takes until a player's Army Morale value drops to 0.
* Either way, if both players' Army Morale values drop to 0 or less on the same turn, then the player with the higher Army Morale value wins a 'tactical victory'.