= Refight 1: Gogard's Last Stand!

== Narrative background

include::partial$note-narrative-summary.adoc[]
(See link:https://thehobby.zone/resources/e40k-compendium/Content/Battles/TheScenarios/Refight1GogardsLastStand.htm[^])

{blank}[TODO: Create a summary of the narrative.]

== Scenario special rules

xref:scenario-special-rules:objectives.adoc[] (only the 'game effects' parts of the Bunker objective rules, not the placement, control or morale effect rules)

== Armies

The main purpose of this scenario is to provide an introductory experience with the <<Historical forces>>.
We have made no attempt to include instructions for more general usage.

However, for ideas to vary this scenario, see <<Scenario variants>>.

== Maps

.Essential terrain
* Roads that converge at a 'Y' junction in the centre of the playing area.
* Seven areas of ruins, close to the roads.

.Deployment
* The Attacker has no deployment edge.
* The Defender has a fixed deployment edge.
* Fixed deployment zones -- refer to the map.

image::map-refight-1-gogards-last-stand.svg[alt="Deployment map for the Gogard's Last Stand scenario",600,450]

[none]
.Legend
* [.conum]#A# Attacker's deployment zone.
* [.conum]#D# Defender's deployment zone (approximate -- actually defined by <<Initial deployment>>). 

== Setup

. Set up terrain as we show at <<Maps>>.
You may set up further terrain as you agree between you.
. Decide which player will be the *Attacker* (Orks) and which the *Defender* (Space Marines).
. Place objectives:
* *Attacker*: You do not set up any objectives for this scenario -- the Defender places markers for your objectives.
* *Defender*: You have no objectives of your own, but you must place markers for two Bunker objectives that will be the focus of your opponent's attack.
You may place these anywhere in the playing area that is at least 15 cm away from any table edge.

== Disposition of forces

*Attacker*: Determine the disposition of your forces.

. Keep your detachment (gargant) at hand for your initial deployment.

*Defender*: Determine the disposition of your forces.

. Choose one detachment to be in position near the 'Y' junction at the start of the battle.
Keep this force at hand for initial deployment.
. Keep your other detachments at hand for deployment in your first turn.

== Initial deployment

. *Defender*: Deploy the detachment that you kept at hand for initial deployment.
You must deploy the units so that they are in, or in base contact with, the ruins that are adjacent to the 'Y' junction (see <<Maps>>).
. *Defender*: Do not deploy your remaining detachments yet.
Instead, place their HQ units anywhere along your deployment edge (on the roads if you like) to indicate where these detachments will enter play during the first turn of the game.
. *Attacker*: Deploy your detachment (gargant) anywhere within the Attacker's deployment zone [.conum]#A# (see <<Maps>>).

== Play the game

include::partial$start-usual.adoc[]

.Reinforcements
*Defender*: When you reach the first Movement phase and it is your turn to complete your moves, put into play the detachments that correspond to the HQ units you placed. Each time you put a detachment into play, measure the movement of its units --  including its HQ unit -- from the point that its HQ unit indicates on your deployment edge.

.New krew
_The gargant has a new krew of lowly Gretchin riggers -- Gogard used the old krew for target practice after a very poor performance in the most recent battle. This new krew are a bit slow to implement the orders that Gogard blares at them..._

In the Movement and Assault phases, the Defender always wins the Initiative.
{blank}[TODO: Clarify -- presumably we should still remove the Defender's Initiative token from the mug?]

.Bunker objectives
When a Bunker objective marker comes under attack, treat it as an Immobilised War Engine unit with the following profile:

include::scenario-special-rules:partial$bunker-data-sheet.adoc[]

== Game length and victory conditions

Play until either the Ork Gargant is destroyed or both Bunker objectives are destroyed.

* If the Defender destroys the Gargant before it has destroyed either bunker, then they win immediately.
* If the Attacker destroys both Bunker objectives, then they win immediately.
* If the Attacker destroys just one Bunker objective and then their Gargant is destroyed, then the game is a draw.

== Historical forces

=== Orks army

Ork Gargants detachment::
1 x Great Gargant (_Korps Grinda_).

{blank}[TODO: Create new data sheet for _Korps Grinda_/Great Gargant. In the meantime, we can refer to the original {e40k} content. (See https://thehobby.zone/resources/e40k-compendium/Content/Resources/Images/Illustrations/BattlesBook/Refight1GogardsLastStand_KorpsGrindaDataCard.gif[Korps Grinda data card^])]

[TIP]
.Ready-made force list in the Detachment Builder
====
link:https://builder.epicremastered.com/print.lc?listname=Ork+army+detachments+for+Refight+1&listurl=https%3A%2F%2Fbuilder.epicremastered.com%2Fchooser.html%3Flist%3DRemastered_Ork_Gargants%26force%3DKorps+Grinda%7E503&submitbuttonname=Submit[Ork army detachments for Refight 1^]
====

=== Space Marines army

Space Marine Armour detachment, _Force Citus_::
4 x Space Marine Land Raider.
Space Marine detachment, _Force Adonis_::
1 x Space Marine Captain; 4 x Space Marine unit, with 4 x Devastator option.
Space Marine detachment, _Force Lentus_::
1 x Space Marine Captain, with Rhino option; 6 x Space Marine unit, with 3 x Rhino option.

[TIP]
.Ready-made force list in the Detachment Builder
====
link:https://builder.epicremastered.com/print.lc?listname=Imperium+army+detachments+for+Refight+1&listurl=https%3A%2F%2Fbuilder.epicremastered.com%2Fchooser.html%3Flist%3DRemastered_SM_Armoured%26force%3DForce%2520Citus%7E501%7E512%7E101x2%7E512%7E101x2%0D%0Ahttps%3A%2F%2Fbuilder.epicremastered.com%2Fchooser.html%3Flist%3DRemastered_SM_Detachment%26force%3DForce+Adonis%7E501%7E502%7E130x1%7E511%7E116x1%7E511%7E116x1%0D%0Ahttps%3A%2F%2Fbuilder.epicremastered.com%2Fchooser.html%3Flist%3DRemastered_SM_Detachment%26force%3DIncompertus%7E501%7E502%7E130x1%7E100x1%7E511%7E114x1%7E100x1%7E511%7E114x1%7E100x1%7E511%7E114x1%7E100x1%0D%0A[Imperium army detachments for Refight 1^]
====

== Scenario variants

This scenario is meant to introduce you to the core rules, and just a few special rules (including those for War Engine units).
So it is quite straightforward, and includes only a small number of units.

You might like to play it a few times before you get into anything more complex.
Even so, you might like to change things a bit to keep it interesting -- so, here are some ideas for variants to try:

* Swap the Defender's heavy weapons infantry for more tanks: Simply drop _Force Adonis_ and add another armoured detachment like _Force Citus_ instead.
* Swap the Defender's tanks for more heavy weapons infantry: Simply drop _Force Citus_ and add another detachment like _Force Adonis_ instead.
* The defending Imperial force could've been very different.
Create a different defending force, which will likely present much more of a challenge for the Attacker:
The Defender may use the Imperial army list to build an army of up to 500 points.
* Gogard's gargant was barely operational when it attacked the Imperial positions.
If it had broken down before it arrived for this battle, then Gogard would have had to cobble together a different force of Orks to attack with.
Create a different attacking force:
The Attacker may use the Ork army list to build an army of up to 500 points.