= Refight 3: The Hellblade Mountains

== Narrative background

include::partial$note-narrative-summary.adoc[]
(See link:https://thehobby.zone/resources/e40k-compendium/Content/Battles/TheScenarios/Refight3TheHellbladeMountains.htm[^])

{blank}[TODO: Create a summary of the narrative.]

== Scenario special rules

xref:scenario-special-rules:army-morale.adoc[]; xref:scenario-special-rules:fortifications.adoc[]; xref:scenario-special-rules:objectives.adoc[]

== Armies

include::partial$refights-armies.adoc[]

== Maps

.Essential terrain
* Two areas of foothills, each flanking the Defender's side of the playing area.

.Deployment
* Fixed deployment edges and zones -- refer to the map.
* The Attacker has two possible edges for 'flanking deployment', one adjacent to each area of foothills.
footnote:[{e40k-diff}
The original {e40k} content is ambiguous about the exact extent of these edges.
We indicate the extent that we think is the most sensible.
]

image::map-refight-3-the-hellblade-mountains.svg[alt="Deployment map for The Hellblade Mountains scenario",600,450]

[none]
.Legend
* [.conum]#A# Attacker's deployment zone.
* [.conum]#D# Defender's deployment zone.
* [.conum]#L# Attacker's left flanking edge.
* [.conum]#R# Attacker's right flanking edge.

== Setup

. Place two areas of foothills, as we show at <<Maps>>.
These represent the lower slopes of a mountain chain.
+
TIP: Use any mountainous or rocky terrain that you have in your terrain collection.
Or, if you lack suitable items, you could use hills and woods instead.
Just try to make the terrain in the two areas of foothills quite dense and hilly, but still passable for ground units.
. xref:get-ready-to-play:set-up-terrain.adoc[Set up terrain] in the rest of the playing area in the standard way.
. Determine at random which player will be the *Attacker* and which the *Defender*.
. Choose your xref:scenario-special-rules:objectives.adoc[objectives], as follows:
* *Attacker*: You must have one objective per 500 points in your army (round fractions up).
You may use any objectives, except for Rescue and Cleanse.
You may either choose from among those available, or pick at random.
* *Defender*: You must have one objective per 1,000 points in your army (rounding fractions *down)*.
You may use only Cleanse objectives.
+
.Number of objectives
====
In a 1,500 point game, the Attacker will have three objectives and the Defender will have one.
====
. Place your objective markers.
The Attacker must place the first objective marker and then the players alternate until they have placed all of the objective markers.

== Disposition of forces

*Attacker*: Determine the disposition of your forces.

. Place all of your Flyer detachments in xref:scenario-special-rules:reserves.adoc[Reserves].
. If you have any detachments that qualify for the Reserves rules on their own merit, place them in Reserves.
. Set aside up to a quarter of your army's maximum points value limit as a *flanking force*.
You may only use complete detachments in the flanking force.
You will put this force into play in the second turn of the game.
. Keep all of your other detachments at hand for your initial deployment.

*Defender*: Determine the disposition of your forces.

. Place all of your Flyer detachments in xref:scenario-special-rules:reserves.adoc[Reserves].
. If you have any detachments that qualify for the Reserves rules on their own merit, place them in Reserves.
. Keep all of your other detachments at hand for your initial deployment.

== Initial deployment

. *Attacker*: In secret, make a note that states which one of the two possible flanking edges your flanking force will arrive on -- left [.conum]#L#, or right [.conum]#R#.
. *Defender*: Deploy all of the detachments that you kept at hand for your initial deployment.
* Deploy within the Defender's deployment zone [.conum]#D# (see <<Maps>>).
* You may also use xref:scenario-special-rules:fortifications.adoc[] if you wish.
+
NOTE: To be clear, the Defender *may* place units in either or both of the two areas of foothills.
. *Attacker*: Deploy within the Attacker's deployment zone [.conum]#A# (see <<Maps>>).

== Play the game

include::partial$start-usual.adoc[]

.Flanking force
*Attacker*: When you reach the Start phase of the second turn, your flanking force arrives.

. Reveal your secret note which states which flanking edge you will use.
. Place the HQ unit of each detachment you have in the flanking force to identify a point on that edge, to indicate where the corresponding detachment will enter play.

When you reach the Movement phase of the second turn, and it is your turn to complete your moves, put your flanking detachments into play.
Each time you put a flanking detachment into play, measure the movement of its units -- including its HQ unit -- from the point that its HQ unit indicates on your flanking edge.

IMPORTANT: The flanking force catches the defenders by surprise -- the Defender may *not* use the Snap Fire rule against units of the Attacker's flanking force on the turn that it arrives.

include::partial$bringing-reserves-detachments-into-play.adoc[]

== Game length and victory conditions

include::partial$standard-army-morale-win-conditions.adoc[]

If this hasn't happened by the end of the 5^th^ turn, or if both players' Army Morale values drop to 0 or less on the same turn, then the player with the highest Army Morale value is the winner.

== Historical forces

=== Orks army

Ork Warband detachment, _Bogrot's Boyz_::
1 x Warboss; 1 x Weirdboy; 12 x Ork unit; 1 x Nobz unit; 9 x Gretchin unit.

Ork Warband detachment, _Da Profeshernalz_::
1 x Warboss; 1 x Weirdboy; 3x Kommandos unit.

Ork Warband detachment, _Der Gunnerz_::
1 x Warboss, with Battlewagon option; 3 x Shooty Boyz unit; 3 x Stompa.

[TIP]
.Ready-made force list in the Detachment Builder
====
link:https://builder.epicremastered.com/print.lc?listname=Ork+army+detachments+for+Refight+3&listurl=https%3A%2F%2Fbuilder.epicremastered.com%2Fchooser.html%3Flist%3DRemastered_Ork_Warband%26force%3DBogrot%60s+Boyz%7E501%7E502%7E505%7E510%7E110x4%7E510%7E110x4%7E510%7E110x4%7E511%7E111x1%7E517%7E117x3%7E517%7E117x3%7E517%7E117x3%0D%0Ahttps%3A%2F%2Fbuilder.epicremastered.com%2Fchooser.html%3Flist%3DRemastered_Ork_Warband%26force%3DDa+Profeshernalz%7E501%7E502%7E505%7E516%7E116x3%0D%0Ahttps%3A%2F%2Fbuilder.epicremastered.com%2Fchooser.html%3Flist%3DRemastered_Ork_Warband%26force%3DDer%2520Gunnerz%7E501%7E502%7E109x1%7E512%7E112x1%7E512%7E112x1%7E512%7E112x1%7E524%7E524%7E524%0D%0A&submitbuttonname=Submit[Ork army detachments for Refight 3^]
====

=== Space Marines army

Space Marine detachment 1, _Force Subodai_::
1 x Space Marine Captain; 2 x Terminator unit; 2 x Scout unit.
+
****
Historically, _Force Subodai_ was the flanking force.
****

Space Marine Armour detachment, _Force Kuanti_::
6 x Land Raider.

Space Marine detachment, _Force Susanowo_::
1 x Space Marine Captain, with Rhino option; 6 x Space Marine unit, with 3 x Rhino option; 1 x Whirlwind.

[TIP]
.Ready-made force list in the Detachment Builder
====
link:https://builder.epicremastered.com/print_21_unitlist.lc?listname=Imperium+army+detachments+for+Refight+3&listurl=https%3A%2F%2Fbuilder.epicremastered.com%2Fchooser.html%3Flist%3DRemastered_SM_Detachment%26force%3DForce+Subodai%7E501%7E502%7E130x1%7E510%7E510%7E513%7E513%0D%0Ahttps%3A%2F%2Fbuilder.epicremastered.com%2Fchooser.html%3Flist%3DRemastered_SM_Armoured%26force%3DForce%2520Kuanti%7E501%7E512%7E101x3%7E512%7E101x3%0D%0Ahttps%3A%2F%2Fbuilder.epicremastered.com%2Fchooser.html%3Flist%3DRemastered_SM_Detachment%26force%3DForce+Susanowo%7E501%7E502%7E130x1%7E100x1%7E511%7E114x1%7E100x1%7E511%7E114x1%7E100x1%7E511%7E114x1%7E100x1%7E524%0D%0A[Imperium army detachments for Refight 3^]
====

== Tactics

At the start of the game, the Defender has their entire army in the playing area, while the Attacker does not.
The Defender must capitalise on this early advantage as much as possible, before the Attacker's flanking force arrives in the second turn.
The Attacker has a golden opportunity to strike at detachments that might otherwise be difficult to reach, especially if they have a relatively slow-moving army.

=== Attacker's tactics

The larger you make your flanking force, the weaker the main force you'll deploy and then manoeuvre in the first turn.
But, a faint heart won't win the day: 
With a strong flanking force, a good battle plan, and the benefit of knowledge that your opponent lacks (that is, you know which flank you'll attack) you have the chance to inflict some crushing casualties.

Note that your flanking force gives you a golden opportunity to put slow-moving but powerful units close to the enemy without a long slog across the battlefield under fire.
This has obvious benefit for the less-mobile armies, such as the Imperial Guard.
But, even the likes of Space Marines have some slow units and allied support options -- and you can't fit a titan in a Thunderhawk Gunship!

Think of the mayhem you could cause with a company of Baneblade super-heavy tanks supported by infantry... or a horde of Goff Orks... or a Chaos Greater Daemon with a retinue of Lesser Daemons...

In any case, whatever the size and composition of your flanking force, it gives you the advantage of knowledge that your opponent doesn't have.
In the early stages of the battle, your opponent is forced to be somewhat conservative and reactive.

=== Defender's tactics

In general, the flank attack is less of a worry for a Defender who has a highly mobile army, and more of a worry for a Defender who has slow-moving army.
And the flank attack might present a more valuable opportunity for an Attacker who has a slow-moving army rather than a highly mobile army.

So, as the Defender, what can you do?
You know for certain that there will be a flank attack, you know when, and you know the maximum strength it could be (in terms of points value).
You just don't know the exact strength or composition of the force.
No matter what army you command, the one thing you can't do is ignore the flanking force.
Things to consider include:

* Make sure that by the end of Turn 1, you've positioned Infantry units to protect any vulnerable Vehicle units.
* Position detachments of close combat specialists such that they will be ready to counter attack or take cover if the flanking force has a lot of firepower.
* Where you don't have a better plan, make use of Overwatch orders to make your detachments more dangerous to approach.
* You know that one of your flanks will face the flanking force while the other will be relatively secure.
Have a plan for what you'll do once you know whether it is your left or right flank that faces the flanking force, and then implement your plan from Turn 2 onwards.