= Refight 4: The Sulphur River

== Scenario special rules

None.

== Narrative background

include::partial$note-narrative-summary.adoc[]
(See link:https://thehobby.zone/resources/e40k-compendium/Content/Battles/TheScenarios/Refight4TheSulphurRiver.htm[^])

{blank}[TODO: Create a summary of the original narrative.]

== Armies

include::partial$refights-armies.adoc[]

== Maps

* Standard deployment edges.
* No deployment zones.
* A river, with two bridges over it.
+
TIP: The exact size and style of the two bridges doesn't matter — just use whatever you have in your terrain collection.
Or, if you lack suitable river and bridge terrain pieces, just improvise them -- use scissors to cut suitable shapes from spare cloth, card or paper.

[.float-group]
--
[.left]
.Long deployment edge
image::map-refight-4-the-sulphur-river-long.svg[alt="Deployment map for The Sulphur River scenario (long deployment edge)",392,294]

[.left]
.Short deployment edge
image::map-refight-4-the-sulphur-river-short.svg[alt="Deployment map for The Sulphur River scenario (short deployment edge)",392,294]

[.left]
.Corner deployment edge
image::map-refight-4-the-sulphur-river-corner.svg[alt="Deployment map for The Sulphur River scenario (corner deployment edge)",392,294]
--

== Setup

. Place a wide river with two bridges across it, as we show at <<Maps>>.
Place the bridges such that each of the two armies can reach the bridge that is nearest to them in the first turn.
. xref:get-ready-to-play:set-up-terrain.adoc[Set up terrain] in the rest of the playing area in the standard way.

== Disposition of forces

Determine the disposition of your forces.

. Place all of your Flyer detachments in xref:scenario-special-rules:reserves.adoc[Reserves].
. If you have any detachments that qualify for the Reserves rules on their own merit, place them in Reserves.
. Keep all of your other detachments at hand for your initial deployment.

== Initial deployment

include::partial$edge-deployment-procedure.adoc[]

== Play the game

Start the game in the usual way: Proceed to the Start phase.

The Sulphur River is highly corrosive, so it is impassable terrain for all ground units (except at the bridges, of course).

== Game length and victory conditions

The goal is to control both bridges.
To control a bridge, you must have at least one of your units on the bridge, and no enemy units.

The game lasts D3+3 turns.
{blank}[TODO: When exactly should we make this roll? Before or after deployment?]

When the game ends, determine the result as follows:

* If a player controls both bridges, then this player wins a major victory.
* If a player controls one bridge and disputes the other, then this player achieves a minor victory.
* If the opposing players each control one bridge, or dispute both bridges, then the result is a draw.

[NOTE.option]
.Victory or Death!
====
For a real bloodbath, if both players agree, ignore the limit of D3+3 turns.
Instead, play this scenario for as many turns as it takes until one player can claim victory by virtue of the fact that their opponent has no units left!
====

== Historical forces
include::partial$footnote-inaccurate-historical-force-lists.adoc[]

=== Orks army

*Ready-made list in the Detachment Builder*: link:https://builder.epicremastered.com/print.lc?listname=Ork+army+detachments+for+Refight+4&listurl=https%3A%2F%2Fbuilder.epicremastered.com%2Fchooser.html%3Flist%3DRemastered_Ork_Warband%26force%3DGazbold%60s+Speed+Boyz%7E501%7E502%7E109x1%7E505%7E516%7E116x3%7E511%7E111x1%7E511%7E111x1%7E511%7E111x1%7E511%7E111x1%7E511%7E111x1%7E511%7E111x1%7E513%7E113x4%7E522%7E122x3%7E520%7E520%7E520%7E520%7E520%7E520%7E520%0D%0Ahttps%3A%2F%2Fbuilder.epicremastered.com%2Fchooser.html%3Flist%3DRemastered_Ork_Warband%26force%3DWaaa-Dreg%2560s%2520Stompas%7E501%7E503%7E505%7E520%7E512%7E112x1%7E512%7E112x1%7E512%7E112x1%7E524%7E524%7E517%7E117x4%7E510%7E110x4%7E510%7E110x4%7E510%7E110x4%0D%0A[Ork army detachments for Refight 4^]

Ork Warband detachment, _Gazbold's Speed Boyz_::
1 x Warboss; 1 x Weirdboy Battle Tower; 3 x Kommando unit; 6 x Nobz unit; 3 x Boarboyz unit; 3 x Bikeboyz unit;  7 x Battlewagon.

Ork Warband detachment, _Waaa-Dreg's Stompas_::
1 x Warboss in Stompa; 1 x Weirdboy Battle Tower; 3 x Shooty Boyz; 2x Stompa; 4 x Gretchin unit; 12 x Ork unit.

=== Space Marines army

*Ready-made list in the Detachment Builder*: link:https://builder.epicremastered.com/print.lc?listname=Imperium+army+detachments+for+Refight+4&listurl=https%3A%2F%2Fbuilder.epicremastered.com%2Fchooser.html%3Flist%3DRemastered_SM_Detachment%26force%3DForce+Firmus%7E501%7E502%7E130x1%7E100x1%7E511%7E100x1%7E115x1%7E511%7E100x1%7E115x1%7E511%7E114x1%7E100x1%7E512%7E124x2%7E510%7E101x1%7E526%7E526%0D%0Ahttps%3A%2F%2Fbuilder.epicremastered.com%2Fchooser.html%3Flist%3DRemastered_SM_Detachment%26force%3DForce+Tardus%7E501%7E502%7E130x1%7E100x1%7E511%7E114x1%7E100x1%7E511%7E114x1%7E100x1%7E526%7E526%0D%0Ahttps%3A%2F%2Fbuilder.epicremastered.com%2Fchooser.html%3Flist%3DRemastered_SM_Armoured%26force%3DForce%2520Supra%7E501%7E514%7E114x3%7E514%7E114x3%0D%0A[Imperium army detachments for Refight 4^]

Space Marine detachment, _Force Firmus_::
1x Space Marine Captain, with Rhino option; 4 x Space Marine unit, with Assault option and Rhino option; 2 x Space Marine unit, with Rhino option; 2 x Space Marine Bike unit; 1 x Terminator unit, with Land Raider option; 2 x Land Raider.

Space Marine detachment, _Force Tardus_::
1 x Space Marine Captain, with Rhino option; 4 x Space Marine unit, with Devastator option and 3 x Rhino option; 2 x Land Raider.

Space Marine Armoured detachment, _Force Supra_::
6 x Whirlwind.

[NOTE.option]
.Historical variant
====
Bridges are often of great strategic and tactical importance, so battles to control them are common.

For a simple variation that can represent other historical battles, if both players agree, simply allow the Space Marines to use the Drop Pods rules to deploy.

{blank}[TODO: This doesn't really make sense as a variation with the listed historical forces, as each of the Space Marine detachments includes vehicles that are not allowed in drop pods (and not just Rhino transport vehicles). I guess either we're supposed to ignore this, or we ignore the given historical lists. It's a bit of an oversight in the original.]
====

.Related information
* xref:scenario-special-rules:drop-pods.adoc[]