= Refight 2: Rescue

== Narrative background

include::partial$note-narrative-summary.adoc[]
(See link:https://thehobby.zone/resources/e40k-compendium/Content/Battles/TheScenarios/Refight2Rescue.htm[^])

{blank}[TODO: Create a summary of the original narrative -- or create a distinct new narrative.]

== Scenario special rules

None.

== Armies

include::partial$refights-armies.adoc[]

== Maps

NOTE: The map and dimensions in the original {e40k} rules content are ambiguous and incompatible with the 180 cm length of the standard playing area.
We believe that the designers intended a 240x120cm playing area for this scenario.
So, we present two different layouts for you to choose from -- one with dimensions we suggest to suit the standard-sized playing area, and one with the original dimensions for use with an extended playing area.

.Suggested layout for standard-sized playing area (180x120 cm)
image::map-refight-2-rescue-180.svg[alt="Deployment map for the Rescue scenario, based on standard playing area (180x120 cm)",392,294]

.Layout for extended playing area (240x120 cm) (recommended)
image::map-refight-2-rescue-240.svg[alt="Deployment map for the Rescue scenario, based on extended playing area (240x120 cm)",499,294]

[none]
.Legend
* [.conum]#A# Attacker's deployment zone.
* [.conum]#D# Defender's garrison deployment zone. 

== Setup

. xref:get-ready-to-play:set-up-terrain.adoc[Set up terrain] in the standard way.
. Decide *at random* which player will be the *Attacker* and which the *Defender*.
. Choose your xref:scenario-special-rules:objectives.adoc[objectives], as follows:
* *Attacker*: You have no objectives of your own.
Instead, your mission is to interfere with the Defender's rescue mission (see <<Game length and victory conditions>>).
* *Defender*: You have a single Rescue objective.
. *Defender*: Place your Rescue objective marker anywhere within the Defender's garrison deployment zone [.conum]#D# (see <<Maps>>).

IMPORTANT: Usually, you can only make the *initial* pickup of a Rescue objective if it is *your* objective.
For this scenario, if the Defender's forces have not picked up the Rescue objective and the Attacker's forces reach a position where they could make the initial pick-up, then they may do so.

== Disposition of forces

*Attacker*: Determine the disposition of your forces.

. Place all of your Flyer detachments in xref:scenario-special-rules:reserves.adoc[Reserves].
. If you have any detachments that qualify for the Reserves rules on their own merit, place them in Reserves.
. Keep all of your other detachments at hand for your initial deployment.

*Defender*: Determine the disposition of your forces.

. Place all of your Flyer detachments in xref:scenario-special-rules:reserves.adoc[Reserves].
. If you have any detachments that qualify for the Reserves rules on their own merit, place them in Reserves.
. Choose detachments up to a total of a quarter of your army's maximum points value limit as the garrison force that protects the vital assassin.
You may only use complete detachments in the garrison force.
Keep this force at hand for initial deployment.
. The remainder of your detachments form your relief force.
Keep this force at hand for initial deployment.

== Initial deployment

. *Defender*: Deploy all of the detachments of your garrison force.
* Deploy within the Defender's garrison deployment zone [.conum]#D# (see <<Maps>>).
. *Attacker*: Deploy all of the detachments that you kept at hand for your initial deployment.
. *Defender*: Do not deploy any detachments yet.
Instead, place HQ units to indicate where the detachments you kept at hand for the relief force will enter play during the first turn of the game.
.. Pick an HQ unit to be first, and place it to indicate any point along your deployment edge.
.. Each other HQ unit you place must indicate a point that is on your deployment edge *and* within 15 cm of the point that your first HQ unit indicates.
You may 'stack' multiple HQ units in a column, to indicate the same point on your deployment edge -- you might want to do this where a road crosses the table edge, for example.
.. Each player may choose one detachment per 1,000 points of the maximum points value limit (or part thereof -- round up) to be a *flanking* detachment, if they wish.
You may place the HQ units of your flanking detachments to indicate any point along your deployment edge, rather than only within 15 cm of the point you indicated with the first HQ unit you placed.

== Play the game

Start the game in the usual way: Proceed to the Start phase.

*Attacker*: You may bring your Reserves detachments into play anywhere along ????.
{blank}[TODO: The original version of this scenario made no accomodation for Reserves. Can we integrate them sensibly?]

*Defender*: You may bring your Reserves detachments into play anywhere along the Defender's deployment edge.

== Game length and victory conditions

To win this scenario, the Defender must exit the Rescue objective marker off of the Defender's deployment edge by the end of Turn 6.

If the Defender has control of the objective marker but hasn't moved it off of the play area by the end of Turn 6, then the result is a draw.

If the Attacker has control of the objective marker at the end of any turn then they win immediately.

Any other result is a draw.

== Historical forces
include::partial$footnote-inaccurate-historical-force-lists.adoc[]

=== Orks army

*Ready-made list in the Detachment Builder*: link:https://builder.epicremastered.com/print.lc?listname=Ork+army+detachments+for+Refight+4&listurl=https%3A%2F%2Fbuilder.epicremastered.com%2Fchooser.html%3Flist%3DRemastered_Ork_Warband%26force%3DGazbold%60s+Speed+Boyz%7E501%7E502%7E109x1%7E516%7E116x3%7E511%7E111x1%7E511%7E111x1%7E511%7E111x1%7E511%7E111x1%7E511%7E111x1%7E511%7E111x1%7E513%7E113x4%7E522%7E122x3%7E506%7E528%7E128x3%7E528%7E128x3%7E528%7E128x1%0D%0Ahttps%3A%2F%2Fbuilder.epicremastered.com%2Fchooser.html%3Flist%3DRemastered_Ork_Warband%26force%3DWaaa-Dreg%2560s%2520Stompas%7E501%7E503%7E520%7E512%7E112x1%7E512%7E112x1%7E512%7E112x1%7E524%7E524%7E517%7E117x4%7E510%7E110x4%7E510%7E110x4%7E510%7E110x4%7E506%0D%0A[Ork army detachments for Refight 2^]

Ork Warband detachment, _Badruk's Speedas_::
1 x Warboss in Stompa; 6 x Ork unit; 6 x Gunwagon.

Ork Warband detachment, _Urglag's Blastas_::
1 x Warboss in Stompa; 3 x Shooty Boyz unit; 3 x Big Gunz.

Ork Warband detachment, _Grizzard da Magnifisunt (an' der Ladz)_::
1 x Warboss in Stompa; 3 x Boarboyz unit; 3 x Stormboyz unit; 3 x Kommandos unit; 3 x Bikeboyz unit; 2 x Gunwagon.

=== Space Marines army

*Ready-made list in the Detachment Builder*: link:https://builder.epicremastered.com/print.lc?listname=Imperium+army+detachments+for+Refight+2&listurl=https%3A%2F%2Fbuilder.epicremastered.com%2Fchooser.html%3Flist%3DRemastered_SM_Detachment%26force%3DForce+Hachiman%7E501%7E502%7E130x1%7E511%7E115x1%7E511%7E115x1%7E513%7E513%0D%0Ahttps%3A%2F%2Fbuilder.epicremastered.com%2Fchooser.html%3Flist%3DRemastered_SM_Armoured%26force%3DForce+Kharira%7E501%7E512%7E112x3%7E512%7E112x2%7E514%7E114x3%7E514%7E114x2%0D%0Ahttps%3A%2F%2Fbuilder.epicremastered.com%2Fchooser.html%3Flist%3DRemastered_SM_Detachment%26force%3DForce%2520Krysha%7E501%7E502%7E130x1%7E100x1%7E511%7E114x1%7E100x1%7E511%7E114x1%7E100x1%7E511%7E114x1%7E100x1%0D%0A&submitbuttonname=Submit[Imperium army detachments for Refight 2^]

Space Marine detachment, _Force Hachiman_::
1 x Space Marine Captain; 4 x Space Marine unit, with Assault option; 2 x Scout unit.
+
****
Historically, _Force Hachiman_ defended the assassin.
****

Space Marine Armoured detachment, _Force Kharira_::
5 x Land Raider; 5 x Whirlwind.

Space Marine detachment, _Force Krysha_::
1 x Space Marine Captain, with Rhino option; 6 x Space Marine unit, with 3 x Rhino option.