= Refight 5: Breakout

== Scenario special rules

xref:scenario-special-rules:fortifications.adoc[]; xref:scenario-special-rules:hidden-setup.adoc[]

== Narrative background

include::partial$note-narrative-summary.adoc[]
(See link:https://thehobby.zone/resources/e40k-compendium/Content/Battles/TheScenarios/Refight5Breakout.htm[^])

{blank}[TODO: Create a summary of the original narrative.]

== Armies

include::partial$refights-armies.adoc[]

== Maps

* Standard deployment edges.
* The Defender's deployment zone extends from their deployment edge to the half-way line.
* The Attacker's deployment zone extends from their deployment edge to 20 cm onto the table.

[.float-group]
--
[.left]
.Long deployment edge
image::map-refight-5-breakout-long.svg[alt="Deployment map for the Breakout scenario (long deployment edge)",392,294]

[.left]
.Short deployment edge
image::map-refight-5-breakout-short.svg[alt="Deployment map for the Breakout scenario (short deployment edge)",392,294]

[.left]
.Corner deployment edge
image::map-refight-5-breakout-corner.svg[alt="Deployment map for the Breakout scenario (corner deployment edge)",392,294]

[none.left]
.Legend
* [.conum]#A# Attacker's deployment zone.
* [.conum]#D# Defender's deployment zone.
--

== Setup

. xref:get-ready-to-play:set-up-terrain.adoc[Set up terrain] in the standard way.
. Determine *at random* which player will be the *Attacker* and which the *Defender*.
. *Defender*: Choose which deployment edge/zone you prefer.
Your opponent gets the opposite edge/zone.
See <<Maps>>.

== Disposition of forces

*Attacker*: Determine the disposition of your forces.

. Place all of your Flyer detachments in xref:scenario-special-rules:reserves.adoc[Reserves].
. If you have any detachments that qualify for the Reserves rules on their own merit, place them in Reserves.
. Keep all of your other detachments at hand for your initial deployment.

*Defender*: Determine the disposition of your forces.
You will have only **half** of the strength of your army for this battle.

. Choose the detachments that will form your defensive force.
+
--
* The total points value of this force must be no more than half of the maximum points value limit for this battle.
* You must choose complete detachments.
+
{blank}[TODO: Clarify: If the Defender chooses any Flyer detachments, should they place them aside to bring into play in the first turn, or should they place them in Reserves?]
--
+
Keep the detachments you choose at hand for your initial deployment.
The rest of your army does not take part in this battle.

== Initial deployment

. *Defender*: You must deploy first.
* Use the xref:scenario-special-rules:hidden-setup.adoc[] rules to deploy all of the detachments that you kept at hand for your initial deployment.
* Deploy within the Defender's deployment zone [.conum]#D# (see <<Maps>>).
* You may also use xref:scenario-special-rules:fortifications.adoc[] if you wish.
+
IMPORTANT: Although you have use of only half your army, you still get one Hidden Setup marker for each Infantry and/or Vehicle detachment that exists in your full army.
{blank}[TODO: Clarify: This scenario seems to have been written with no thought to Flyer or War Engine detachments. Should we explicitly exclude them, or should we make proper allowance for either or both of these types of detachment? If the latter, are there game balance issues to account for? How do Flyer detachments affect the number of ground-based detachments the Attacker must exit off of the Defender's table edge for a win? (Probably they shouldn't affect this at all, so the Attacker must be mindful that an excess of Flyer detachments could be a hindrance.)]

== Play the game

Start the game in the usual way: Proceed to the Start phase.

== Game length and victory conditions

To win this scenario, the Attacker must exit at least half of the detachments in their army off of the Defender's table edge by the end of Turn 6.
Detachments reduced to half strength or less do not count.
{blank}[TODO: For an odd number of attacking detachments, should we round up or round down for the number that must exit for a win...?]

Any other result is a win for the Defender.

== Historical forces
include::partial$footnote-inaccurate-historical-force-lists.adoc[]

=== Ork army

*Ready-made list in the Detachment Builder*: link:https://builder.epicremastered.com/print.lc?listname=Ork+army+detachments+for+Refight+5&listurl=https%3A%2F%2Fbuilder.epicremastered.com%2Fchooser.html%3Flist%3DRemastered_Ork_Warlord%26force%3DWarlord+Nah-Badun+an%60+der+Retinue%7E502%7E109x1%7E506%7E511%7E111x1%7E517%7E117x2%7E528%7E128x2%0D%0Ahttps%3A%2F%2Fbuilder.epicremastered.com%2Fchooser.html%3Flist%3DRemastered_Ork_Kult%26force%3DDa%2520Chargerz%7E501%7E502%7E522%7E122x3%7E528%7E128x3%7E528%7E128x3%0D%0Ahttps%3A%2F%2Fbuilder.epicremastered.com%2Fchooser.html%3Flist%3DRemastered_Ork_Warband%26force%3DNaffgul%60s+Shooty+Boyz%7E501%7E503%7E512%7E112x3%7E517%7E117x4%7E524%7E524%7E510%7E110x4%7E510%7E110x4%7E510%7E110x4%0D%0A[Ork army detachments for Refight 5^]

Ork Warlord detachment, _Warlord Nah-Badun an' der Retinue_::
1 x Warlord, with Battlewagon option; 1 x Weirdboy Battle Tower; 1 x Nobz unit; 1 x Gretchin unit; 2 x Battlewagon.

Ork Kult of Speed detachment, _Da Chargerz_::
1 x Warboss; 6 x Battlewagon; 3 x Bikeboyz.

Ork Warband detachment, _Naffgul's Shooty Boyz_::
1 x Warboss in Stompa; 3 x Shooty Boyz unit; 2 x Stompa; 4 x Gretchin unit; 12 x Ork unit.

=== Space Marine army

*Ready-made list in the Detachment Builder*: link:https://builder.epicremastered.com/print.lc?listname=Imperium+army+detachments+for+Refight+5&listurl=https%3A%2F%2Fbuilder.epicremastered.com%2Fchooser.html%3Flist%3DRemastered_SM_Detachment%26force%3DForce+Specula%7E501%7E502%7E130x1%7E511%7E116x1%7E511%7E116x1%7E511%7E116x1%0D%0Ahttps%3A%2F%2Fbuilder.epicremastered.com%2Fchooser.html%3Flist%3DRemastered_SM_Detachment%26force%3DForce+Ceptio%7E501%7E502%7E130x1%7E101x1%7E511%7E115x1%7E511%7E115x1%7E511%7E115x1%0D%0Ahttps%3A%2F%2Fbuilder.epicremastered.com%2Fchooser.html%3Flist%3DRemastered_SM_Detachment%26force%3DForce%2520Odium%7E501%7E526%7E511%7E114x1%7E100x1%7E511%7E114x1%7E100x1%7E511%7E114x1%7E100x1%7E511%7E114x1%7E100x1%7E511%7E114x1%7E100x1%7E511%7E114x1%7E100x1%7E524%7E524%0D%0A[Imperium army detachments for Refight 5^]

Space Marine detachment, _Force Specula_::
1 x Space Marine Captain;  6 x Space Marine unit, with Devastator option. 

Space Marine detachment, _Force Ceptio_::
1 x Space Marine Captain, with Land Raider option; 6 x Space Marine unit, with Assault option. 
+
****
Historically it was _Force Specula_ and _Force Ceptio_ that formed the Imperial line where the Orks planned to break out.
****
Space Marine detachment, _Force Odium_::
1 x Land Raider; 12 x Space Marine unit, with 6 x Rhino option; 2 x Whirlwind.