= Select a scenario

The scenario that you select determines the overall nature of the battle that you intend to play.

Each scenario offers a unique combination of rules for setup and play, to model different types of confrontation and victory conditions.

We detail a range of scenarios at xref:scenarios:scenarios.adoc[].

[NOTE]
====
You don't necessarily have to decide what scenario you will play before you choose armies -- it can also be fun to try to build a versatile army first, and then adapt to the situation that you find yourself in later.
However, this may limit your choice of scenarios, as some scenarios specify restrictions or requirements for the composition of one or both armies.
====

== Types of scenario

Scenarios can take many different forms, but {project-name} presents them broadly as follows:

* *Refight scenarios*: Recreations of 'historical' battles in the _Warhammer 40,000_ universe.
These scenarios showcase the use of narratives to create engaging, unique battles.
* *Battle scenarios*: Outlines of various different types of confrontation that are common on battlefields across the galaxy.
These scenarios give you generalised frameworks for your battles, but include little in the way of narrative -- that's up to you.
* *The Fog of War*: A method to generate lots of different match-ups -- in effect, a great way to generate lots of different scenarios that force you and your opponent to adapt to the unexpected.

Some of the scenarios use common special rules that model the effects of fortifications, morale, and so on (xref:scenario-special-rules:scenario-special-rules.adoc[]).
Some specify rules that are unique to those scenarios.

== How to select a scenario to play

Of course, you and your opponent can simply agree on a scenario to play, invent a new one, or plan several to play in a sequence as a mini-campaign.
Or, you may prefer to select a scenario at random.

TIP: If you're new to the game, it's best to start with the simplest scenarios.
We recommend xref:scenarios:refight-1-gogards-last-stand.adoc[] and xref:scenarios:refight-4-the-sulphur-river.adoc[].

=== Random scenario selection

If you'd like to select a scenario at random, consult this table:

.Scenario generator table (roll a D6)
[options"autowidth, header"]
|===
|1pass:[<br>]Refight: Roll another D6 |2 to 5pass:[<br>]Battle: Roll another D6 |6

|1. xref:scenarios:refight-1-gogards-last-stand.adoc[]
|1. xref:scenarios:battle-1-meeting-engagement.adoc[]
.6+|xref:scenarios:the-fog-of-war.adoc[]

|2. xref:scenarios:refight-2-rescue.adoc[]
|2. xref:scenarios:battle-2-escalating-engagement.adoc[]

|3. xref:scenarios:refight-3-the-hellblade-mountains.adoc[]
|3. xref:scenarios:battle-3-dawn-assault.adoc[]

|4. xref:scenarios:refight-4-the-sulphur-river.adoc[]
|4. xref:scenarios:battle-4-blitzkrieg.adoc[]

|5. xref:scenarios:refight-5-breakout.adoc[]
|5. xref:scenarios:battle-5-ambush.adoc[]

|6. Re-roll, or opt for xref:scenarios:the-fog-of-war.adoc[]
|6. xref:scenarios:battle-6-planetary-assault.adoc[]

|===